### ISSUE TITLE
Call to undefined function socket_create()

### ISSUE THREAD

**Issue by AaronMcHale** [NuVotifier/votifier2-php#2]
Just downloaded and tried to use this library, however got the following error, quick scan of the code confirms that function indeed is not defined.

`Fatal error: Call to undefined function Imaginarycode\Votifier2\socket_create() in <dir>\Server.php on line 36`

Any help would be appreciated,
Thanks
Aaron

**Comment by minecrafter** [comment]
Please make sure the `socket` extension is loaded and works.
